# Generated by Django 5.0.3 on 2024-03-13 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicalStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nct_id", models.CharField(max_length=50, unique=True)),
                ("org_study_id", models.CharField(max_length=50)),
                ("organization_name", models.CharField(max_length=255)),
                ("brief_title", models.CharField(max_length=255)),
                ("official_title", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("status_verified_date", models.DateField(default=None, null=True)),
                ("expanded_access", models.BooleanField(default=False)),
                (
                    "start_date",
                    models.DateField(
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value="2000-01-01"
                            )
                        ],
                    ),
                ),
                (
                    "primary_completion_date",
                    models.DateField(
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value="2000-01-01"
                            )
                        ],
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value="2000-01-01"
                            )
                        ],
                    ),
                ),
                (
                    "study_first_submit_date",
                    models.DateField(
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value="2000-01-01"
                            )
                        ],
                    ),
                ),
                (
                    "study_first_submit_qc_date",
                    models.DateField(
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value="2000-01-01"
                            )
                        ],
                    ),
                ),
                (
                    "study_first_post_date",
                    models.DateField(
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value="2000-01-01"
                            )
                        ],
                    ),
                ),
                (
                    "last_update_submit_date",
                    models.DateField(
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value="2000-01-01"
                            )
                        ],
                    ),
                ),
                (
                    "last_update_post_date",
                    models.DateField(
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value="2000-01-01"
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("other_names", models.CharField(max_length=255)),
                ("arm_group_labels", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ArmGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.clinicalstudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=255)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.clinicalstudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "study",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.clinicalstudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brief_summary", models.TextField()),
                ("detailed_description", models.TextField()),
                (
                    "study",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.clinicalstudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_type", models.CharField(max_length=50)),
                ("phases", models.CharField(max_length=50)),
                ("allocation", models.CharField(max_length=50)),
                ("intervention_model", models.CharField(max_length=50)),
                ("intervention_model_description", models.TextField()),
                ("primary_purpose", models.CharField(max_length=50)),
                ("masking", models.CharField(max_length=50)),
                (
                    "study",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.clinicalstudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Eligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eligibility_criteria", models.TextField()),
                ("healthy_volunteers", models.BooleanField(default=False)),
                ("sex", models.CharField(max_length=10)),
                ("minimum_age", models.CharField(max_length=20)),
                ("maximum_age", models.CharField(max_length=20)),
                ("stdAges", models.CharField(default="all", max_length=100, null=True)),
                (
                    "study",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.clinicalstudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MiscInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_holder", models.CharField(max_length=20)),
                (
                    "study",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.clinicalstudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measure", models.TextField()),
                ("description", models.TextField()),
                ("time_frame", models.CharField(max_length=255)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.clinicalstudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pmid", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("citation", models.TextField()),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.clinicalstudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SponsorCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("class_type", models.CharField(max_length=50)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.clinicalstudy",
                    ),
                ),
            ],
        ),
    ]
