# Generated by Django 5.0.3 on 2024-03-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="masking",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="design",
            name="phases",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
