# Generated by Django 5.0.3 on 2024-03-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_design_masking_alter_design_phases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="allocation",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
