# Generated by Django 5.0.3 on 2024-03-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_design_allocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="intervention_model",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
