# Generated by Django 5.0.3 on 2024-03-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_design_intervention_model_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="other_names",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
