# Generated by Django 5.0.3 on 2024-03-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_intervention_other_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorcollaborator",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
