# Generated by Django 5.0.3 on 2024-03-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_sponsorcollaborator_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorcollaborator",
            name="class_type",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
