# Generated by Django 5.0.3 on 2024-03-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_sponsorcollaborator_class_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactlocation",
            name="state",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
