# Generated by Django 5.0.3 on 2024-03-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_alter_clinicalstudy_brief_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eligibility",
            name="eligibility_criteria",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="eligibility",
            name="maximum_age",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="eligibility",
            name="minimum_age",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="eligibility",
            name="sex",
            field=models.CharField(default=None, max_length=10),
        ),
    ]
