# Generated by Django 5.0.3 on 2024-03-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_alter_eligibility_eligibility_criteria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eligibility",
            name="sex",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
